name: Release Workflow

env:
  DOTNET_NOLOGO: true

on:
  workflow_call:
    inputs:
      publish:
          description: Publish to nuget or not
          default: false
          type: boolean

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with: { dotnet-version: 8.0.x }

      - name: Setup wasm-tools
        run: dotnet workload install wasm-tools

      - name: Setup tailwindcss
        run: npm install -g tailwindcss

      - name: Setup Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4.2
        id: nbgv
        with: { setAllVars: true }

      - name: Restore
        working-directory: src/WizardCounter.UI.Wasm
        run: |
          npm install
          dotnet restore

      - name: Build
        working-directory: src/WizardCounter.UI.Wasm
        run: dotnet build -c Release --no-restore

      - name: Publish
        if: ${{ inputs.publish }}
        working-directory: src/WizardCounter.UI.Wasm
        shell: pwsh
        run: |
          .\css.ps1 -publish
          dotnet publish --no-restore

      # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to WizardCounter
        if: ${{ inputs.publish }}
        run: sed -i 's/<base href="\/" \/>/<base href="\/WizardCounter\/" \/>/g' artifacts/src/publish/WizardCounter.UI.Wasm/release/wwwroot/index.html

        # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        if: ${{ inputs.publish }}
        run: cp artifacts/src/publish/WizardCounter.UI.Wasm/release/wwwroot/index.html artifacts/src/publish/WizardCounter.UI.Wasm/release/wwwroot/404.html

      - name: Setup Pages
        if: ${{ inputs.publish }}
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ inputs.publish }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifacts/src/publish/WizardCounter.UI.Wasm/release/wwwroot

      - name: Deploy to GitHub Pages
        if: ${{ inputs.publish }}
        id: deployment
        uses: actions/deploy-pages@v4