name: Build

env:
  DOTNET_NOLOGO: true

on:
  workflow_dispatch:
  pull_request:
    branches: dev
    paths:
      - "version.json"
      - "src/**/*.cs"
      - "src/**/*.csproj"

jobs:
  Build:
    uses: panoukos41/WizardCounter/.github/workflows/_ci.yaml@main